config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'articles#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("id DESC").page(params[:page]).per(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: '投稿できたよー' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

    def logged_in?
      session[:user_id].nil?
    end

    def login_check
      unless logged_in?
        flash[:alert] = "ログインしてください"
        redirect_to login_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    admin = params[:session][:password]
    if admin == ENV['LOGIN_PASSWORD']
      log_in
      redirect_to root_url
    else
      render 'new'
    end
    # puts params[:session][:password]
    #   console.log()
    # else
    #   redirect_to 'root_path'
    # end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y年%m月%d日　%H:%M　")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in
    session[:user_id] = 1
  end

  def current_user
    if session[:user_id]
      @current_user = 'taketori'
    end
  end

  def logged_in?
    session[:user_id].nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.haml
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .field
    = form.text_field :title
  .field
    = form.label :深く聞かせて？
    = form.rich_text_area :content
  .actions{style: "margin:3%" }
    = form.submit '飛んでけ〜', class: 'btn btn-primary'

app/views/articles/edit.html.haml
%h1 Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%p#notice= notice
- if !logged_in?
  .articlesContainer
    - @articles.each do |article|
      .articleContainer
        .display-4.articleTitle= link_to article.title, article
        %p.lead.articleMiniContent= article.content
        %hr.my-4
        %p.articleTime= simple_time(article.updated_at)
        %br/

  = paginate @articles, class: "articlePaginate"
  = render 'share/new_post'
- else
  = render 'share/session'
= debug(params) if Rails.env.development?

app/views/articles/new.html.haml
-if !logged_in?
  .newAritcleContainer
    %h1.newArticleTitle どんな具合？
    = render 'form', article: @article
    = link_to 'タイムライン', root_path, class: "btn btn-info"
-else
  = render 'share/session'

app/views/articles/show.html.haml
-if !logged_in?
  .showArticleContainer
  %p
    %h1.showArticleTitle= @article.title
    %hr.style13
    .showArticleContent
      = @article.content
    %p.showArticleTime= simple_time(@article.created_at)
  .showButtons
    = link_to "削除", @article, class: "btn btn-raised btn-danger articleButtons", method: :delete, data: { confirm: 'Are you sure?' }
    = link_to 'タイムラインへ', root_path, class: "btn btn-info"
-else
  = render 'share/session'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyDiary
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'share/header' 
    = yield

app/views/share/_header.html.haml
.headerContainer
  .hederTitle= link_to 'Taketori Diary', root_path
  - if !logged_in?
    = link_to 'logout', logout_path, method: :delete, class: 'btn btn-danger logoutButton'

app/views/share/_new_post.html.haml
= link_to image_tag("post.png", width: '100vh', height: '100vh', alt: "new post"), new_article_path, class: 'new_post_image'

app/views/share/_session.html.haml
.newSessionContainer
  %h1.newSessionTitle 合言葉は？
  .newSessionFormContainer
    = form_with(scope: :session, url: login_path, local: true ) do |f|
      .field
        = f.password_field :password, class: 'pass_field'
        .actions
          = f.submit '照合'

= debug(params) if Rails.env.development?